name: untitled1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  path: ^1.8.0
  flutter_local_notifications: ^17.2.2  # Added the package here
  intl: ^0.18.0
  path_provider: ^2.1.4
  csv: ^6.0.0
  convert: ^3.1.1
  fl_chart: ^0.69.0
  flutter_pdfview: ^1.3.3
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.7
  dash_chat_2: ^0.0.20
  sqflite: ^2.0.0+4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.11
  flutter_inappwebview: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/textbook.pdf
